name: Test Versioning

on:
  push:
    branches:
      - Master

jobs:
  update-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Print package.json
      run: cat package.json

    - name: Read Version from package.json
      run: |
        jq . package.json
        VERSION=$(jq -r .version package.json)
        echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV
        echo "Extracted version: $VERSION"
