name: Update Unity Package

on:
  push:
    branches:
      - Master  # Ensure this matches the case of your branch name

jobs:
  update-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get current date
      run: echo "CURRENT_DATE=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: Define new tag
      run: echo "NEW_TAG=release-${{ env.CURRENT_DATE }}" >> $GITHUB_ENV

    - name: Update Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.NEW_TAG }}
        name: Release ${{ env.NEW_TAG }}
        body: 'Release generated on ${{ env.CURRENT_DATE }}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
